### ISSUE TITLE
API stats are not kept when the container is restarted

### ISSUE THREAD

**Issue by My-Random-Thoughts** [Minituff/nautical-backup#170]
It seems that if I stop and restart the Nautical Backup container the stats given by the API are reset to 0.
It would be nice to keep the stats so that they can be referenced upon a restart.

Are they meant to be stored somewhere?

**Comment by Minituff** [comment]
Hey @My-Random-Thoughts,

I re-worked the way Nautical handles the database in version [2.0.0](https://github.com/Minituff/nautical-backup/releases/tag/v2.0.0) and now it should be preserved during restarts.

But the database will *not* be preserved during updates unless you mount the `/config` directory.

I'm going to close this issue for now, but if it still doesn't work, please re-open it.

-James
