### ISSUE TITLE
No backup due to spaces in folder naming on Linux

### ISSUE THREAD

**Issue by MMaximuss** [Minituff/nautical-backup#224]
Thanks for your hard work on this project! It's incredibly helpful for managing backups.

I noticed a small issue regarding folder naming on Linux systems. Since Linux doesn't accept spaces in folder names, I encountered some difficulties when using the default format example you provided (DEST_DATE_FORMAT=Nautical Backup - %Y-%m-%d). On Linux systems, this example only creates folders, but no backup takes place. For me it was fixed by using no spaces.

Edit: I also have a small question. Is it possible to have the backups automatically deleted after a rotation of, for example, a week? Is this maybe possible with Lifecycle Hooks and the 'find' and 'delete'/'rm' command in linux?

**Comment by Minituff** [comment]
> Thanks for your hard work on this project! It's incredibly helpful for managing backups.

Thank you! This is good to hear :)

---

This is a good catch.
I will most likely change the default from `Nautical Backup - %Y-%m-%d` to maybe something like `Nautical_Backup-%Y-%m-%d` to fix the spacing issue.

--- 
> Is it possible to have the backups automatically deleted after a rotation of, for example, a week? Is this maybe possible with Lifecycle Hooks and the 'find' and 'delete'/'rm' command in linux?

I was thinking about this too. I'm wondering what the best approach would be.

### Option 1 
Create a tiny `.nbackup` file or something in each *destination* directory that can hold some metadata (like the date for example), then I can have nautical find these files and delete them accordingly.
* This option would still allow the database to be deleted and not required.

### Option 2
When creating a backup, I could save all the directories and their metadata into a database (or even a json file) and use that for determining which files to delete.
* This option creates no external file, but would mean that if the database is lost then cleanup would not be possible.

**Comment by MMaximuss** [comment]
Thanks for you quick reaction.

> I was thinking about this too. I'm wondering what the best approach would be.

Both options sound good. Option 1 seems easiest to me. With a log file and meta file in each destination folder. I'm looking forward to the release ;-)

**Comment by Minituff** [comment]
Sounds good. I'll quickly update the default value in the next release. 

The versioned backups might take a little longer to implement, but I'll keep you posted.

**Comment by Minituff** [comment]
Hey @MMaximuss , 
revisting this after I looked around the codebase.

I'm actually only seeing `Nautical Backup - %Y-%m-%d` inside the [Docs](https://minituff.github.io/nautical-backup/arguments/#destination-folder-format) in the example.

In the code, I actually have ` %Y-%m-%d` as the default when you set `USE_DEST_DATE_FOLDER=true`

Do you still run into this problem you set?:
```properties
USE_DEST_DATE_FOLDER=true
```
And leave `DEST_DATE_FORMAT` unset? 

If that's the case then I will just update the docs and I won't need to change the code itself :)

**Comment by MMaximuss** [comment]
I followed your instructions in the docs. Updating the docs for Linux users will be a fix.

**Comment by Minituff** [comment]
Awesome. I updated the docs here: https://github.com/Minituff/nautical-backup/commit/2bf1e258d26561c27404ec5babf5fa071948a2ee.

Thanks for pointing this out.

**Comment by MMaximuss** [comment]
> I was thinking about this too. I'm wondering what the best approach would be.

I solved it this way:

`- POST_BACKUP_EXEC=find /app/destination/* -maxdepth 1 -name "*_backup" -type d -ctime +28 | xargs rm -rf`

This rule deletes the directory after 28 days. The name command may not have been necessary, but it gives me a sense of security. Works perfect!

**Comment by Minituff** [comment]
This is awesome! Thanks @MMaximuss !
