### ISSUE TITLE
Support for Docker Socket Proxy

### ISSUE THREAD

**Issue by legacy3** [Minituff/nautical-backup#230]
Hey there,

Really enjoying nautical backup — awesome work! I was wondering if it could be configured to support Docker socket proxies by using the `DOCKER_HOST` environment variable. This change would help point the Docker API interactions to a proxy instead of directly accessing `/var/run/docker.sock`.

**Quick suggestions for this:**
- Could be cool to adapt the tool to use Docker client libraries that recognize `DOCKER_HOST`.
- Maybe a quick test with tools like `docker-proxy` or `socat` to check compatibility?

**Documentation:**
If this is already possible, adding a note in the docs would be super helpful. If not, it might be a useful feature to include in future updates.

Thanks for considering this! 

Cheers,

**Comment by Minituff** [comment]
Thanks for the suggestion. I don't think this is possible yet--or atleast I haven't tried it. 

I'll do some digging to see how I can add this.

**Comment by Minituff** [comment]
Would you want to use something like this: https://docs.linuxserver.io/images/docker-socket-proxy ??

**Comment by Minituff** [comment]
Update on this. I tested out https://github.com/Tecnativa/docker-socket-proxy. It seems to be working and I will add this feature to the next release (v3.0)

**Comment by Minituff** [comment]
Hey so I think version 3 is going to take much longer than I originally thought. It didn't take much to get Docker Socket Proxy working so I added it in [v2.8.0](https://github.com/Minituff/nautical-backup/releases/tag/v2.8.0)

I added a new section to the docs that go over how to set it up:
https://minituff.github.io/nautical-backup/docker-socket-proxy/


Let me know if it works :)
