### ISSUE TITLE
[question] how to use something else than rsync?

### ISSUE THREAD

**Issue by wsw70** [Minituff/nautical-backup#240]
_Sorry for posting a question in the Issues section but Discussions are not enabled._

The documentation mentions at https://minituff.github.io/nautical-backup/advanced/remote-backups/ that other solutions than rsync can be used to perform the backup. is this documented somewhere?

> Ideally, you would configure Nautical to create a backup at a `destination` folder, then point that folder to a remote backup solution

Do you mean that I would need to make a copy of the data via rsync and use this as the backup source for, say, Borg?

**Comment by Minituff** [comment]
> Do you mean that I would need to make a copy of the data via rsync and use this as the backup source for, say, Borg?

Yes, exactly.

**Comment by wsw70** [comment]
> Yes, exactly.

OK thanks! This means that I need to provision twice the size of my data (data + backup). This won't be a problem but it is good to know.

My actual backups are done by Borg (both local and remote), so it will be some more.

**Comment by Minituff** [comment]
> OK thanks! This means that I need to provision twice the size of my data (data + backup). This won't be a problem but it is good to know.

Yup, you're exactly right about that.


> My actual backups are done by Borg (both local and remote), so it will be some more.

Nice, I've heard some requests to incorporate Borg. I'd be interested to see your configuration once you got it all working. Maybe we could add it to the docs to help others out with the same idea?
