### ISSUE TITLE
rsync case sensitivity not working right

### ISSUE THREAD

**Issue by Nyan96** [Minituff/nautical-backup#264]
So i have this label in one of my containers on my Synology. It should exclude the "ASDF" folder
`      - "nautical-backup.rsync-custom-args=--exclude=ASDF`

However, in the nautilus backup log it outputs this. Note the capitalization change.
'DEBUG: RUNNING: 'rsync -raq --exclude=asdf '

And it still backs up the "ASDF" folder. For some reason its converting the upper  case letters to lower case.

Am I doin something wrong?

**Comment by Minituff** [comment]
Interesting, I can see if `.lower()` is being applied or if there is another reason it be being cast to lowercase.

**Comment by Minituff** [comment]
I can confirm this bug is happening just as you stated. It was in fact a `.lower()` was being applied when it should not have. I fixed this bug and added a new test case that should catch this from now on.

**Comment by Minituff** [comment]
This has been fixed in the latest release: https://github.com/Minituff/nautical-backup/releases/tag/v2.3.3
