### ISSUE TITLE
Incorrect last_cron reported by API

### ISSUE THREAD

**Issue by robflate** [Minituff/nautical-backup#308]
I have `CRON_SCHEDULE: "0 0 * * *"` set but the API reports `"last_cron": "09/07/24 12:00",`

If I check my Homepage Dashboard widget after the CRON has run at midnight but before 12:00 noon the next day it shows as a time in the future;

<img width="408" alt="Screenshot 2024-09-07 at 07 08 25" src="https://github.com/user-attachments/assets/3a37ca79-8649-408a-a519-76a724e05a2d">

Here's the output of `/api/v1/nautical/dashboard`;
```
{
  "next_cron": {
    "cron": "0 0 * * *",
    "tz": "Europe/London",
    "1": [
      "Sunday, September 08, 2024 at 12:00 AM",
      "09/08/24 00:00"
    ],
    "2": [
      "Monday, September 09, 2024 at 12:00 AM",
      "09/09/24 00:00"
    ],
    "3": [
      "Tuesday, September 10, 2024 at 12:00 AM",
      "09/10/24 00:00"
    ],
    "4": [
      "Wednesday, September 11, 2024 at 12:00 AM",
      "09/11/24 00:00"
    ],
    "5": [
      "Thursday, September 12, 2024 at 12:00 AM",
      "09/12/24 00:00"
    ]
  },
  "next_run": "09/08/24 00:00",
  "last_cron": "09/07/24 12:00",
  "number_of_containers": 70,
  "completed": 49,
  "skipped": 21,
  "errors": 0,
  "backup_running": 21
}
```

If I check the date in the container `docker exec nautical-backup date` it reports correctly.

Is there some issue with midnight being interpreted as 12:00 rather than 00:00?

**Comment by Minituff** [comment]
> Is there some issue with midnight being interpreted as 12:00 rather than 00:00?

This would be my guess too, I'll take a look and see.

**Comment by Minituff** [comment]
I think I may have figured it out. The time format I was using in the API was the 12hr time instead of the 24hr time. Hopefully this update fixes the issue. 

I updated the `dashboard` API endpoint in version [v2.6.0-alpha1](https://github.com/Minituff/nautical-backup/releases/tag/v2.6.0-alpha1) and PR https://github.com/Minituff/nautical-backup/pull/311

Could you test it out and let me know what you think?

How to force update the YML
```yaml
    image: minituff/nautical-backup:2.6.0-alpha1
```

**Comment by Minituff** [comment]
So I tested it out with my personal stack yesterday and it seems to be working:

<img width="380" alt="Screenshot 2024-09-09 at 8 40 05 AM" src="https://github.com/user-attachments/assets/07f81d1b-1755-44f4-b55e-f7d4b12625a5">
<img width="251" alt="Screenshot 2024-09-09 at 8 40 45 AM" src="https://github.com/user-attachments/assets/5acc2628-f5a5-40ed-b1f2-1ef954e58d0b">

I'm going to close this issue for now, but please re-open it if you test it and it doesn't work.

**Comment by robflate** [comment]
Brilliant. Works correctly now.
