### ISSUE TITLE
Cron job fails 

### ISSUE THREAD

**Issue by gaodes** [Minituff/nautical-backup#320]
Since I updated to v2.6.3 from v2.6.0 the cron jobs are not working anymore. I get the following error:
```shell
nautical-backup  | INFO: Nautical Backup Version: 2.6.3
nautical-backup  | INFO: Connected to database at '/config/nautical-db.json'
nautical-backup  | INFO: API listening on port 8069...
nautical-backup  | INFO: Initialization complete. Awaiting CRON schedule: 54 16 * * *
nautical-backup  | Traceback (most recent call last):
nautical-backup  |   File "/usr/local/bin/nautical", line 18, in 
nautical-backup  |     from app.api.config import Settings
nautical-backup  | ModuleNotFoundError: No module named 'app'
```  
However, if I manually call for a backup, everything works as expected.
Any ideas?

**Comment by Minituff** [comment]
Hey thanks for reporting this. I was working on a permissions ticket https://github.com/Minituff/nautical-backup/issues/314 and I merged some changes in that broke this.

I fixed this in version [2.6.4](https://github.com/Minituff/nautical-backup/releases/tag/v2.6.4).
