### ISSUE TITLE
Add Dependency: 7zip to image

### ISSUE THREAD

**Issue by valdearg** [Minituff/nautical-backup#339]
Would it be possible to get the 7zip dependency added into the docker image.

Working on a post backup script which will archive the files, 7z seems to be the best for the compression to size ratio.

Seems to be available in the same pipeline: https://pkgs.alpinelinux.org/package/v3.18/main/x86_64/7zip

**Comment by Minituff** [comment]
Yeah, I can do that 😀

**Comment by Minituff** [comment]
Merged in version [2.6.9](https://github.com/Minituff/nautical-backup/releases/tag/v2.6.9)

**Comment by valdearg** [comment]
Sweet, that works. Cheers for that.

If anyone wants it/to use as a starting point for their own, the script is below. I have nautical set to backup to a separate folder which is the date (container_name/2024-10-08 for example), this script just 7zs up that folder.:

```
#!/usr/bin/env bash

# Checking env vars
echo "NB_EXEC_CONTAINER_NAME: $NB_EXEC_CONTAINER_NAME"
echo "NB_EXEC_CONTAINER_ID: $NB_EXEC_CONTAINER_ID"

# Directory containing the backups
backup_dir="${backup_dir:-/app/destination/$NB_EXEC_CONTAINER_NAME}"

echo "$backup_dir"

# Loop through all directories in the backup directory
for archive in "$backup_dir"/*; do
    if [ -d "$archive" ]; then
        archive_name="${archive}.7z"

        if [ -f "$archive_name" ]; then
            echo "Archive already exists: $(basename "$archive_name") - removing folder"
            echo "Archive path: $archive"
            rm -rf "$archive"
        else
            echo "Creating archive: $(basename "$archive_name")"
            7z a -t7z -mx=9 "$archive_name" "$archive"/* -xr!metadata/cache/items

            if [ -f "$archive_name" ]; then
                echo "Archive exists: $(basename "$archive_name") - removing folder"
                echo "Archive path: $archive"
                rm -rf "$archive"
            fi
        fi
    fi
done
```

That goes in the config folder that's mounted in the container, mark it as executable with +x, then you can use labels/env vars in the container to run it after: `"nautical-backup.exec.after=/config/7z_folders.sh"`

Can run it outside the container also by setting the env vars, e.g.:

`NB_EXEC_CONTAINER_NAME=audiobookshelf backup_dir=/media/Rin/Backups/DockerNautical/audiobookshelf nautical-backup/config/7z_folders.sh`

**Comment by Minituff** [comment]
Thanks for this! I was actually just going to ask if you could share your config. 

I'm thinking of making some kind of "Examples" page with common setups and I think yours is a good start.
