### ISSUE TITLE
Additional folders skips the destination date folder

### ISSUE THREAD

**Issue by cantchooseaname8** [Minituff/nautical-backup#365]
All of my containers are backed up to a new folder with the current date (main_folder/dated_folder). However, when I add an additional folder, it isn't added to the dated folder. Instead, it is added to the main folder. Here are my env variables:

    environment: # Optional variables
      - TZ=America/Los_Angeles
      - CRON_SCHEDULE_ENABLED=false
      - CRON_SCHEDULE=0 9 1,15 * *
      - BACKUP_ON_START=false
      - SKIP_CONTAINERS=
      - SKIP_STOPPING=nautical-backup,homebridge
      - USE_DEST_DATE_FOLDER=true
      - DEST_DATE_FORMAT=%Y-%m-%d
      - DEST_DATE_PATH_FORMAT=date/container
      - REPORT_FILE=false
      - ADDITIONAL_FOLDERS=env-files
      - ADDITIONAL_FOLDERS_WHEN=before 

I'm trying to back up the env-files folder which is already located in the /app/source volume of the container. Is this the intended behavior of the additional folders variable or did I set something up wrong? I might be overlooking something obvious, but can't seem to figure out how to make the additional folder backup to the same folder as the containers.

**Comment by Minituff** [comment]
I think you may have encountered a bug. The way you're understanding would make the most sense.

I'll test on my end to verify, but I'm assuming I'll need to put out an update to fix this.

**Comment by cantchooseaname8** [comment]
Thanks for such a quick response. I thought I was definitely doing something wrong. Good to know I’m not going crazy!

**Comment by Minituff** [comment]
Hi @cantchooseaname8, I pushed out an update that I think fixes this issue. I haven't tested it out in my Homelab yet, but I did create a unit test for it and it passes that test.

Let me know what you think. Make sure you update to version [2.7.0](https://github.com/Minituff/nautical-backup/releases/tag/v2.7.0) or greater.


If, everything works, I'll close out this issue :)

**Comment by cantchooseaname8** [comment]
Just updated and added the new environment variable. It’s working perfect now. Thank you for pushing that update so quickly!!!

**Comment by Minituff** [comment]
No problem. Glad it works!!
