### ISSUE TITLE
Use exection date as source of date instead of actual backup date 

### ISSUE THREAD

**Issue by mrjk** [Minituff/nautical-backup#380]
I have the following backup configuration, with forlder timestamps to seconds:

```
services:
  image: minituff/nautical-backup:2.8
  ...
  environment:
    - USE_DEST_DATE_FOLDER=true
    - DEST_DATE_FORMAT=infra_archives_paperless/%Y-%m-%d_%H-%M-%S
```

When I run 2 backups, I get this:
```
.
`-- infra_archives_paperless
    |-- 2024-11-24_14-26-43
    |   `-- infra_archives_paperless-ngx-db-1
    |-- 2024-11-24_14-26-44
    |   |-- infra_archives_paperless-ngx-webserver-1
    |   |-- data
    |   `-- share
    |-- 2024-11-24_14-28-10
    |   `-- infra_archives_paperless-ngx-db-1
    `-- 2024-11-24_14-28-11
        |-- infra_archives_paperless-ngx-webserver-1
        |-- data
        `-- share
```

So I've many output directories, split by backup time:
```
# Backup 1
infra_archives_paperless/2024-11-24_14-26-43
infra_archives_paperless/2024-11-24_14-26-44

# Backup 2
infra_archives_paperless/2024-11-24_14-28-10
infra_archives_paperless/2024-11-24_14-28-11
```

However, I'd like to have the folowing output:
```
# Backup 1
infra_archives_paperless/2024-11-24_14-26-43

# Backup 2
infra_archives_paperless/2024-11-24_14-28-10
```

Is it possible to get this result ? I checked out quickly the code, (here https://github.com/Minituff/nautical-backup/blob/main/app/backup.py#L468 ), and indeed timestamp seems to be calculated each time a container backup start. While this definitely make sense, I'd like to have an option to use the nautilus start timestamp instead of the container start timestamp.

Do you feel that make sense ? Do you have time to implement it ? If not I'll consider to make a pull request, if you're open to this feature.

Potential implementation:
* Env var: `USE_CONTAINER_BACKUP_DATE=true` (default is `false` to keep existing behavior). If true, backup timestamp is generated when the container is backuped. If false, backup timestamp is generated when nautilus actually starts. This is useful to keep precise timestamps in the same directories when `USE_DEST_DATE_FOLDER=true` and `DEST_DATE_FORMAT=%Y-%m-%d_%H-%M-%S` goes to seconds or to timestamps.
* labels: I don't think this option should be available on labels, but maybe I'm wrong on this one. Or maybe yes, idk.

**Comment by Minituff** [comment]
Got it. Yeah I think I can make this change for you.

**Comment by Minituff** [comment]
Hey @mrjk, 

I added this feature for you. The docs doing go live until I merge into `main`, but you can see what I changed in the PR.
https://github.com/Minituff/nautical-backup/pull/382

Could you test out version [2.9.0-beta1](https://github.com/Minituff/nautical-backup/releases/tag/v2.9.0-beta1) and let me know if it works.

**Comment by mrjk** [comment]
How whaooo, you're Lucky Luke; the man who code faster than his own shadow ! :sunglasses:  Ok, I try this asap to give you feedbacks. 

Also, I think I found another bug when timestamp is enabled, it seems it does not respect anymore `override-source-dir`, it use the container name instead. I'll make another report for this one.

**Comment by mrjk** [comment]
Ok, so far it work as expected, but only the first time:
```
`-- infra_archives_paperless
    |-- 2024-11-24_15-47-32  # Worked as expected
    |   |-- infra_archives_paperless-ngx-db-1         # Other bug here: override-source-dir not respected anymore
    |   |-- infra_archives_paperless-ngx-webserver-1  # Other bug here
    |   |-- data                                      # Work well here
    |   `-- share
    |-- 2024-11-24_15-51-12 # Did not worked as expected   # This ticket bug, second call use the old behavior
    |   `-- infra_archives_paperless-ngx-db-1
    |-- 2024-11-24_15-51-13 # Did not worked as expected
    |   |-- infra_archives_paperless-ngx-webserver-1
    |   |-- data
    |   `-- share
    `-- Backup\ Report\ -\ 2024-11-24.txt
```

I feel it's super weird, I'm wondering if something is wrong on my setup, because I don't understand this behavior. I'm investigating to give you more feedbacks ...

**Comment by Minituff** [comment]
Hmm. Thanks for testing it out.

I'll do some more testing on my end too. You could also take a look at the PR I made. I did it rather quickly so I might have made a mistake 😕

**Comment by mrjk** [comment]
Ok, amazing, v2.9.0-beta2 works as expected :) It's good for me. Thanks again for your amazing support.

**Comment by Minituff** [comment]
Heck yea! Awesome!! I'll move that up to `main` and then I can start on your other issue :)

**Comment by mrjk** [comment]
Ho and there is another typo in logging message, I updated the code review ;)

**Comment by Minituff** [comment]
Thanks so much for all your help!! I appreciate you catching my silly mistakes

**Comment by Minituff** [comment]
Full release https://github.com/Minituff/nautical-backup/releases/tag/v2.9.0 is out
