### ISSUE TITLE
Links in latest change log point to localhost

### ISSUE THREAD

**Issue by adamshand** [Minituff/nautical-backup#82]
FYI, in the latest change log the documentation links point to localhost.

<img width="541" alt="image" src="https://github.com/Minituff/nautical-backup/assets/130651/c24bf636-87fd-4063-abea-db8217c934f3">

**Comment by Minituff** [comment]
Thanks for the call-out. Looks like I used my local environment for the links instead of the production one. Should be fixed now: https://github.com/Minituff/nautical-backup/releases/tag/v1.2.0
