### ISSUE TITLE
How to group containers in batches ./. stop start ?

### ISSUE THREAD

**Issue by ecatphi8** [Minituff/nautical-backup#88]
Not a bug but a question

Let's say I have a few applications deployed using docker compose ( paperless, netbox,....)
Each "stack" has a few containers ( db/web/redis....)
How to make sure the whole stack is stopped before backup then restarted after the backup  
Otherwise, if Ibackup the database container without stopping the web container.... bad things happens

I really like the label way of configuring nautical, being able to stop/start per stack would be awsome.

**Comment by Minituff** [comment]
This is a good idea. Currently, there is no *native* way to support this. 

I suppose you could use `Additional folders` as a workaround for now?

But I definitely will be adding this. 

So maybe what you would do is create a label like
```properties
labels:
  nautical-backup.group=Paperless
```
Then anything with that label will be stopped & backed up together.

**Comment by ecatphi8** [comment]
That would fit !
The loop might need some refactoring
I suspect two passes might be needed
first pass:  fill a map[group] to  array of containers
second pass: loop through map 
   loop for all containers in group
     stop 
   end
   loop for all containers in group
     backup
   end
   loop for all containers in group
     start 
   end

**Comment by Minituff** [comment]
Yeah I agree, will for sure require some refactoring to make it work, but I think it's do-able. 

I'm pushing out an update to merge the `api -> main` branch soon, then after that I'll get started on the grouping feature for the next release.

**Comment by Minituff** [comment]
Hey, I added this feature in [Version 2.0.0](https://github.com/Minituff/nautical-backup/releases/tag/v2.0.0).

I am going to close this issue, but if this feature is not working or you would like some more features, feel free to reopen it or create a new issue.
